const mongoose = require("mongoose");
const TeamMember = require("../models/TeamMember");

const MONGO_URI = "mongodb://localhost:27017/TeamDB"; // change if needed

const teamData = [
  // ================= Faculty Advisor =================
  {
    name: "Dr. A. K. Bakthavatsalam",
    role: "Faculty Advisor",
    subteam: null,
    Department: "Energy and Environment Engineering",
    photoUrl: "/Team/Dr_A_K_Bakthavatsalam.png",
    email: "baktha@nitt.edu",
    description: "Guiding innovation and research initiatives in engineering and technology",
    order: 1
  },
  {
    name: "Sivanesan",
    role: "Admin Executive",
    subteam: null,
    Department: null,
    photoUrl: "/Team/Sivaneshan.jpg",
    email: "sivaneshan@nitt.edu",
    description: "Overseeing facility management and operations",
    order: 2
  },
  {
    name: "Arjun B K",
    role: "Technical Executive",
    subteam: null,
    Department: "Electrical and Electronics Engineering",
    photoUrl: "/Team/Arjun_B_K.png",
    year: "Final Year",
    email: "arjunbharathikumar@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Leading key initiatives in the student team",
    order: 3
  },
  {
    name: "Alok Verma",
    role: "Facility Executive",
    subteam: null,
    Department: "Mechanical Engineering",
    photoUrl: "/Team/Alok_Verma.png",
    year: "Final Year",
    email: "alokverma4237@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Contributing to team leadership and projects",
    order: 4
  },
  {
    name: "Coming Soon...",
    role: "Project Management Head",
    subteam: null,
    Department: "-----------------",
    photoUrl: null,
    year: "Final Year",
    email: "scient@nitt.edu",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Contributing to team leadership and projects",
    order: 7
  },
  {
    name: "Alan Prakash",
    role: "External Affairs Executive",
    subteam: null,
    Department: "Civil Engineering",
    photoUrl: "/Team/Alan_Prakash.jpg",
    year: "Final Year",
    email: "alanprakash55@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Driving technical and organizational efforts",
    order: 5
  },
  {
    name: "Mahalakshmi R",
    role: "Internal Affairs Executive",
    subteam: null,
    Department: "Metallurgical and Materials Engineering",
    photoUrl: "/Team/Mahalakshmi_R.png",
    year: "Final Year",
    email: "mahalakshmi0ramesh@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Coordinating team activities and outreach",
    order: 6
  },
  {
    name: "Advaith S",
    role: "Manager",
    subteam: "DevOps",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Advaith _S.jpg",
    year: "PreFinal Year",
    email: "advaith.t20@gmail.com",
    linkedin: "https://www.linkedin.com/in/advaith-s-35692a2ab/",
    instagram: "https://www.instagram.com/advaith.fyi/",
    description: "Leading DevOps initiatives and technical projects",
    order: 7
  },
  {
    name: "Dendukuri Soumya",
    role: "Manager",
    subteam: "Corporate Communications",
    Department: "Civil Engineering",
    photoUrl: "/Team/Dendukuri_Soumya.jpg",
    year: "PreFinal Year",
    email: "soumya95507@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Coordinating corporate communications and outreach",
    order: 8
  },
  {
    name: "Divyansh Kumar Agrawal",
    role: "Manager",
    subteam: "DevOps",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Divyansh_Kumar_Agrawal.jpg",
    year: "PreFinal Year",
    email: "divyanshkumaragrawal80@gmail.com",
    linkedin: "https://www.linkedin.com/in/divyansh-agrawal-4a806a2b1",
    instagram: "https://www.instagram.com/divyansh_agr_80",
    description: "Driving DevOps solutions and technical development",
    order: 9
  },
  {
    name: "Gargi Gupta",
    role: "Manager",
    subteam: "Corporate Communications",
    Department: "Mechanical Engineering",
    photoUrl: "/Team/Gargi_Gupta.jpg",
    year: "PreFinal Year",
    email: "gargi.gupta0601@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Managing corporate communications and events",
    order: 10
  },
  {
    name: "Indhumathi V",
    role: "Manager",
    subteam: "DevOps",
    Department: "Production Engineering",
    photoUrl: "/Team/Indhumathi_V.jpg",
    year: "PreFinal Year",
    email: "indhu23.v@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Enhancing team outreach through communications",
    order: 11
  },
  {
    name: "Kakularam Saiprakash Reddy",
    role: "Manager",
    subteam: "DevOps",
    Department: "Civil Engineering",
    photoUrl: "/Team/Kakularam_Saiprakash_Reddy.png",
    year: "PreFinal Year",
    email: "kakularamsaiprakashreddy9@gmail.com",
    linkedin: "https://www.linkedin.com/in/sai-prakash-reddy-kakularam-323273280/",
    instagram: "https://www.instagram.com/saiprakashreddy.k/",
    description: "Contributing to DevOps and technical innovation",
    order: 12
  },
  {
    name: "Mona M S",
    role: "Manager",
    subteam: "Corporate Communications",
    Department: "Metallurgical and Materials Engineering",
    photoUrl: "/Team/Mona_M_S.jpg",
    year: "PreFinal Year",
    email: "mona.shivakkumar@gmail.com",
    linkedin: "https://www.linkedin.com/in/mona-m-s-10228b300",
    instagram: "https://www.instagram.com/_.mona._.01._/",
    description: "Leading corporate communication strategies",
    order: 13
  },
  {
    name: "Pranesh S K",
    role: "Manager",
    subteam: "Creatives",
    Department: "Metallurgical and Materials Engineering",
    photoUrl: "/Team/Pranesh_S_K.jpg",
    year: "PreFinal Year",
    email: "pranesh26erd@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Coordinating team communications and events",
    order: 14
  },
  {
    name: "Shivam Mishra",
    role: "Manager",
    subteam: "DevOps",
    Department: "Instrumentation and Control Engineering",
    photoUrl: "/Team/Shivam_Mishra.jpg",
    year: "PreFinal Year",
    email: "realshivat2606@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Supporting DevOps projects and technical tasks",
    order: 15
  },
  {
    name: "Tanisha Narasimman",
    role: "Manager",
    subteam: "Corporate Communications",
    Department: "Metallurgical and Materials Engineering",
    photoUrl: "/Team/Tanisha_Narasimman.jpg",
    year: "PreFinal Year",
    email: "tanishanarasimman777@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Promoting team initiatives through communications",
    order: 16
  },
  {
    name: "Vedavarshini",
    role: "Manager",
    subteam: "Creatives",
    Department: "Electrical and Electronics Engineering",
    photoUrl: "/Team/Vedavarshini.jpg",
    year: "PreFinal Year",
    email: "vedavarshiniv2@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Crafting creative visuals for team projects",
    order: 17
  },
  {
    name: "Thejashvee",
    role: "Manager",
    subteam: "Corporate Communications",
    Department: "Instrumentation and Control Engineering",
    photoUrl: "/Team/Thejashvee.jpg",
    year: "PreFinal Year",
    email: "thejubabu1@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Enhancing team visibility through communications",
    order: 18
  },
  {
    name: "Sanskar Sharma",
    role: "Deputy Manager",
    subteam: "DevOps",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Sanskar_Sharma.jpg",
    year: "2nd Year",
    email: "sharmasanskar7201@gmail.com",
    linkedin: "https://www.linkedin.com/in/sanskar-sharma-0515a9319",
    instagram: "https://www.instagram.com/_sekhar_sharma/",
    description: "Contributing to DevOps and technical tasks",
    order: 19
  },
  {
    name: "Hasini Thakkallapelly",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Hasini_Thakkallapelly.jpg",
    year: "2nd Year",
    email: "hasini.thakkallapelly34@gmail.com",
    linkedin: "https://www.linkedin.com/in/hasinithakkallapelly/",
    instagram: "https://www.instagram.com/hasini_rufg/",
    description: "Assisting in corporate communications",
    order: 20
  },
  {
    name: "S. Nayan Vamsi",
    role: "Deputy Manager",
    subteam: "DevOps",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Nayan_Vamsi.jpg",
    year: "2nd Year",
    email: "nayanvamsi@gmail.com",
    linkedin: "https://www.linkedin.com/in/nayan-vamsi-sunkarapalli-b2a93536b/",
    instagram: "https://www.instagram.com/___nayan__007/",
    description: "Contributing to DevOps and technical development",
    order: 21
  },
  {
    name: "Kamalakannan Ravichandran",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Civil Engineering",
    photoUrl: "/Team/Kamalakannan_R.jpg",
    year: "2nd Year",
    email: "kamalakannanravichandran@gmail.com",
    linkedin: "https://www.linkedin.com/in/kamalakannan-ravichandran-843b662a5",
    instagram: "https://www.instagram.com/kamalakannanravichandran11",
    description: "Supporting corporate communications efforts",
    order: 22
  },
  {
    name: "Chebrolu Bhuvan",
    role: "Deputy Manager",
    subteam: "DevOps",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Chebrolu_Bhuvan.jpg",
    year: "2nd Year",
    email: "bhuvanchebrolu@gmail.com",
    linkedin: "https://www.linkedin.com/in/bhuvan-chebrolu-5835641b2/",
    instagram: "https://www.instagram.com/bhuvaneshwar2966/",
    description: "Assisting in DevOps projects and technical tasks",
    order: 23
  },
  {
    name: "S. Janani Krithika",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Civil Engineering",
    photoUrl: "/Team/S_Janani_Krithika.jpg",
    year: "2nd Year",
    email: "jananikrithika9@gmail.com",
    linkedin: "https://www.linkedin.com/in/janani-krithika-26b019334",
    instagram: "https://www.instagram.com/janani.krithika/",
    description: "Contributing to team outreach and communications",
    order: 24
  },
  {
    name: "Bhuvan Prakash",
    role: "Deputy Manager",
    subteam: "DevOps",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Bhuvan_prakash.jpg",
    year: "2nd Year",
    email: "bhuvanprakash06@gmail.com",
    linkedin: "https://www.linkedin.com/in/bhuvan-prakash-b20a7a379",
    instagram: "https://www.instagram.com/bhuvan._prakash/",
    description: "Supporting DevOps initiatives and technical projects",
    order: 25
  },
  {
    name: "Pavithra M A",
    role: "Deputy Manager",
    subteam: "Creatives",
    Department: "Electronics and Communication Engineering",
    photoUrl: "/Team/Pavithra_M_A.jpg",
    year: "2nd Year",
    email: "pavithra55ma@gmail.com",
    linkedin: "https://www.linkedin.com/in/pavithra-m-a-b52476324",
    instagram: "https://www.instagram.com/pavithra_m_a",
    description: "Designing creative content for team initiatives",
    order: 26
  },
  {
    name: "Aryan Nagle",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Instrumentation and Control Engineering",
    photoUrl: "/Team/Aryan_Nagle.jpg",
    year: "2nd Year",
    email: "aryannagle362@gmail.com",
    linkedin: "https://www.linkedin.com/in/aryan-nagle-a22840343",
    instagram: "https://www.instagram.com/a_ryann06/",
    description: "Assisting in corporate communications and events",
    order: 27
  },
  {
    name: "Bhuvaneswaran B R",
    role: "Deputy Manager",
    subteam: "Creatives",
    Department: "Metallurgical and Materials Engineering",
    photoUrl: "/Team/Bhuvaneswaran_B_R.jpg",
    year: "2nd Year",
    email: "bhuvaneswaranbr@gmail.com",
    linkedin: "https://www.linkedin.com/in/bhuvaneswaran-b-r-7b5725322",
    instagram: "https://www.instagram.com/i__am_bhuvi02",
    description: "Creating visuals for team projects and events",
    order: 28
  },
  {
    name: "Nandhana V",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Metallurgical and Materials Engineering",
    photoUrl: "/Team/Nandhana_V.jpg",
    year: "2nd Year",
    email: "nandhanav2006@gmail.com",
    linkedin: "https://www.linkedin.com/in/nandhana-v-312a81379/",
    instagram: "https://www.instagram.com/_nandhana_v/",
    description: "Supporting team communication strategies",
    order: 29
  },
  {
    name: "Vishal Durai",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Metallurgical and Materials Engineering",
    photoUrl: "/Team/Vishal.jpg",
    year: "2nd Year",
    email: "vishaldurai06@gmail.com",
    linkedin: "https://www.linkedin.com/in/vishal-d-7ab937312",
    instagram: "https://www.instagram.com/_._vizhal_._",
    description: "Contributing to team outreach efforts",
    order: 30
  },
  {
    name: "Vaidya Nilay Vivek",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Electrical and Electronics Engineering",
    photoUrl: "/Team/Vaidya_Nilay_Vivek.jpg",
    year: "2nd Year",
    email: "nilayvaidya2005@gmail.com",
    linkedin: "https://www.linkedin.com/in/nilay-vaidya-051993333",
    instagram: "https://www.instagram.com/nilay0341",
    description: "Supporting team outreach and communications",
    order: 31
  },
  {
    name: "Muhesh Alagappan Thiyagarajan",
    role: "Deputy Manager",
    subteam: "Creatives",
    Department: "Electrical and Electronics Engineering",
    photoUrl: "/Team/Muhesh.png",
    year: "2nd Year",
    email: "muheshat416@gmail.com",
    linkedin: "https://www.linkedin.com/in/muhesh-a-t-39b0aa354/",
    instagram: "https://www.instagram.com/mu.he.sh/",
    description: "Crafting creative designs for team initiatives",
    order: 32
  },
  {
    name: "Lakshana S",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Electrical and Electronics Engineering",
    photoUrl: "/Team/Lakshana.jpg",
    year: "2nd Year",
    email: "lakshana4486@gmail.com",
    linkedin: "https://www.linkedin.com/in/lakshana-s-aa437a326/",
    instagram: "https://www.instagram.com/lakshana2848",
    description: "Assisting in team communication efforts",
    order: 33
  },
  {
    name: "Priyanshu Mahajan",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Instrumentation and Control Engineering",
    photoUrl: null,
    year: "2nd Year",
    email: "priyanshumahajan6@gmail.com",
    linkedin: "https://www.linkedin.com/in/priyanshu-mahajan-102a14379",
    instagram: "https://www.instagram.com/priyanshu.mahajan_",
    description: "Contributing to corporate communications",
    order: 34
  },
  {
    name: "Jatin Suresh Subramani",
    role: "Deputy Manager",
    subteam: "Creatives",
    Department: "Architecture",
    photoUrl: "/Team/Jatin_S_S.jpg",
    year: "2nd Year",
    email: "jatinsuresh5647@gmail.com",
    linkedin: "https://www.linkedin.com/in/jatin-suresh-a732bb309",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Designing visuals for team projects",
    order: 35
  },
  {
    name: "Poluru Saketh Koundinya",
    role: "Deputy Manager",
    subteam: "DevOps",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Saketh.jpg",
    year: "2nd Year",
    email: "polurusaketh@gmail.com",
    linkedin: "https://www.linkedin.com/in/saketh-poluru-515b91315",
    instagram: "https://www.instagram.com/granger__47",
    description: "Supporting DevOps and technical development",
    order: 36
  },
  {
    name: "Samarth Pattewar",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Instrumentation and Control Engineering",
    photoUrl: "/Team/Samarth.jpg",
    year: "2nd Year",
    email: "samarthbpattewar@gmail.com",
    linkedin: "https://www.linkedin.com/in/samarth-pattewar-64191034a",
    instagram: "https://www.instagram.com/psam_arth",
    description: "Assisting in team outreach and communications",
    order: 37
  },
  {
    name: "Muhammad Yousuf",
    role: "Deputy Manager",
    subteam: "Creatives",
    Department: "Architecture",
    photoUrl: "/Team/Muhammad_Yousuf.jpg",
    year: "2nd Year",
    email: "muhammadyousuf5winners@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/__you._.suf",
    description: "Creating engaging visual content",
    order: 38
  },
  {
    name: "Meeduti Rithwik Sundar",
    role: "Deputy Manager",
    subteam: "Creatives",
    Department: "Architecture",
    photoUrl: "/Team/M_Rithwik_Sundar.jpg",
    year: "2nd Year",
    email: "srinivasreddykaripireddy566@gmail.com",
    linkedin: "https://www.linkedin.com/in/meeduri-rithwik-002172329",
    instagram: "https://www.instagram.com/scient_nitt/",
    description: "Contributing to creative design projects",
    order: 39
  },
  {
    name: "Jayasri R",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Civil Engineering",
    photoUrl: "/Team/Jayasri_R.jpg",
    year: "2nd Year",
    email: "jayasrijha2006@gmail.com",
    linkedin: "https://in.linkedin.com/in/jayasri-rajasundaram-143a4a291",
    instagram: "https://www.instagram.com/jayasri_jerry22",
    description: "Supporting corporate communications",
    order: 40
  },
  {
    name: "Harshitha R",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Computer Science and Engineering",
    photoUrl: "/Team/Harshitha_R2.png",
    year: "2nd Year",
    email: "harshitharaman123@gmail.com",
    linkedin: "https://www.linkedin.com/company/scientnitt/",
    instagram: "https://www.instagram.com/harshey238",
    description: "Assisting in team communication efforts",
    order: 41
  },
  {
    name: "Krishvinraam Mohan",
    role: "Deputy Manager",
    subteam: "DevOps",
    Department: "Production Engineering",
    photoUrl: null,
    year: "2nd Year",
    email: "krishvinraam3@gmail.com",
    linkedin: "https://www.linkedin.com/in/krishvinraam-mohan-5a82261ab/",
    instagram: "https://www.instagram.com/krishvin_3_/",
    description: "Contributing to DevOps and technical projects",
    order: 42
  },
  {
    name: "Monashri S",
    role: "Deputy Manager",
    subteam: "Creatives",
    Department: "Metallurgical and Materials Engineering",
    photoUrl: "/Team/Monashri_S.jpg",
    year: "2nd Year",
    email: "mshrismail@gmail.com",
    linkedin: "https://www.linkedin.com/in/monashri-s-1b900b37a",
    instagram: "https://www.instagram.com/monashri_._",
    description: "Crafting creative visuals for the team",
    order: 43
  },
  {
    name: "Swathi Chokalingam",
    role: "Deputy Manager",
    subteam: "Corporate Communications",
    Department: "Electrical and Electronics Engineering",
    photoUrl: "/Team/Swathi_Chokalingam.jpg",
    year: "2nd Year",
    email: "swathinit2028@gmail.com",
    linkedin: "https://www.linkedin.com/in/swathi-chokalingam-590b39379",
    instagram: "https://www.instagram.com/swathi_chok",
    description: "Supporting team outreach and communications",
    order: 44
  }
];

const seedDB = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ MongoDB connected");

    await TeamMember.deleteMany({});
    console.log("🧹 Old data cleared");

    const inserted = await TeamMember.insertMany(teamData); // Re-assign to capture
    console.log("Inserted roles:", inserted.map(m => m.role));
    console.log("🌱 Team data seeded successfully!");

    mongoose.connection.close();
  } catch (err) {
    console.error("❌ Error seeding database:", err);
    mongoose.connection.close();
  }
};

seedDB();