const mongoose = require("mongoose");
const TeamMember = require("../models/TeamMember");
const {
  Dr_Baktha,
  Chebrolu_Bhuvan,
  Sanskar_Sharma,
  M_Rithwik_Sundar,
  Aryan_Nagle,
  Bhuvan_prakash,
  Swathi_Chokalingam,
  Jatin_S_S,
  Lakshana_S,
  Nandhana_V,
  Vishal_Durai,
  Hasini_Thakkallapelly,
  Kamalakannan_Ravichandran,
  S_Nayan_Vamsi,
  Bhuvaneswaran_B_R,
  Muhesh_Alagappan_Thiyagarajan,
  Jayasri_R,
  Monashri_S,
  Pavithra,
  harshita,
  samarth,
  Vaidya_Nilay_Vivek,
  S_janani,
  Poluru_Saketh_Koundinya,
  Muhammad_Yousuf,
  Advaith_S,
  Dendukuri_Soumya,
  Drishya_Anil,
  Gargi_Gupta,
  Indhumathi_V,
  Thejashvee,
  Divyansh_Kumar_Agrawal_Manager,
  Kakularam_Saiprakash_Reddy,
  Mona_M_S,
  Pranesh_S_K,
  Shivam_Mishra,
  Tanisha_Narasimman,
  Vedavarshini,
  Arjun_B_K,
  Alok_Verma,
  Alan_Prakash,
  Mahalakshmi_R
} = require('../assets');


const MONGO_URI = "mongodb://localhost:27017/TeamDB"; // change if needed

const teamData = [
  // ================= Faculty Advisor =================
  {
        name: "Dr. A. K. Bakthavatsalam",
        role: "Faculty Advisor",
        subteam: null,
        Department: "Energy and Environment Engineering",
        photoUrl: "/Team/Dr_A_K_Bakthavatsalam.png",
        email: "baktha@nitt.edu",
        image: Dr_Baktha,
        bio: "Guiding innovation and research initiatives in engineering and technology"
      },
      {
        name: "Arjun B K",
        role: "Core Member",
        subteam: "Technical Executive",
        Department: null,
        photoUrl: "/Team/Arjun_B_K.png",
        year: "4th Year",
        email: "arjunbharathikumar@gmail.com",
        linkedin: null,
        instagram: null,
        image: Arjun_B_K,
        bio: "Leading key initiatives in the student team"
      },
      {
        name: "Alok Verma",
        role: "Core Member",
        subteam: "Facility Executive",
        Department: null,
        photoUrl: "/Team/Alok_Verma.png",
        year: "4th Year",
        email: "alokverma4237@gmail.com",
        linkedin: null,
        instagram: null,
        image: Alok_Verma,
        bio: "Contributing to team leadership and projects"
      },
      {
        name: "Alan Prakash",
        role: "Core Member",
        subteam: "External Affairs Executive",
        Department: null,
        photoUrl: "/Team/Alan_Prakash.jpg",
        year: "4th Year",
        email: "alanprakash55@gmail.com",
        linkedin: null,
        instagram: null,
        image: Alan_Prakash,
        bio: "Driving technical and organizational efforts"
      },
      {
        name: "Mahalakshmi R",
        role: "Core Member",
        subteam: "Internal Affairs Executive",
        Department: null,
        photoUrl: "/Team/Mahalakshmi_R.png",
        year: "4th Year",
        email: "mahalakshmi0ramesh@gmail.com",
        linkedin: null,
        instagram: null,
        image:  Mahalakshmi_R,
        bio: "Coordinating team activities and outreach"
      },
       {
        name: "Advaith S",
        role: "Manager",
        subteam: "DevOps",
        Department: null,
        photoUrl: "/Team/Advaith _S.jpg",
        year: "3rd Year",
        email: "advaith.t20@gmail.com",
        linkedin: "https://www.linkedin.com/in/advaith-s-35692a2ab/",
        instagram: "https://www.instagram.com/advaith.fyi/",
        image: Advaith_S,
        bio: "Leading DevOps initiatives and technical projects"
      },
      {
        name: "Dendukuri Soumya",
        role: "Manager",
        subteam: "Corporate Communications",
        Department: null,
        photoUrl: "/Team/Dendukuri_Soumya.jpg",
        year: "3rd Year",
        email: "soumya95507@gmail.com",
        linkedin: null,
        instagram: null,
        image: Dendukuri_Soumya,
        bio: "Coordinating corporate communications and outreach"
      },
      {
        name: "Divyansh Kumar Agrawal",
        role: "Manager",
        subteam: "DevOps",
        Department: null,
        photoUrl: "/Team/Divyansh_Kumar_Agrawal.jpg",
        year: "3rd Year",
        email: "divyanshkumaragrawal80@gmail.com",
        linkedin: "https://www.linkedin.com/in/divyansh-agrawal-4a806a2b1",
        instagram: "https://www.instagram.com/divyansh_agr_80",
        image: Divyansh_Kumar_Agrawal_Manager,
        bio: "Driving DevOps solutions and technical development"
      },
      {
        name: "Gargi Gupta",
        role: "Manager",
        subteam: "Corporate Communications",
        Department: null,
        photoUrl: "/Team/Gargi_Gupta.jpg",
        year: "3rd Year",
        email: "gargi.gupta0601@gmail.com",
        linkedin: null,
        instagram: null,
        image: Gargi_Gupta,
        bio: "Managing corporate communications and events"
      },
      {
        name: "Indhumathi V",
        role: "Manager",
        subteam: "Corporate Communications",
        Department: null,
        photoUrl: "/Team/Indhumathi_V.jpg",
        year: "3rd Year",
        email: "indhu23.v@gmail.com",
        linkedin: null,
        instagram: null,
        image: Indhumathi_V,
        bio: "Enhancing team outreach through communications"
      },
      {
        name: "Kakularam Saiprakash Reddy",
        role: "Manager",
        subteam: "DevOps",
        Department: null,
        photoUrl: "/Team/Kakularam_Saiprakash_Reddy.png",
        year: "3rd Year",
        email: "kakularamsaiprakashreddy9@gmail.com",
        linkedin: "https://www.linkedin.com/in/sai-prakash-reddy-kakularam-323273280/",
        instagram: "https://www.instagram.com/saiprakashreddy.k/",
        image: Kakularam_Saiprakash_Reddy,
        bio: "Contributing to DevOps and technical innovation"
      },
      {
        name: "Mona M S",
        role: "Manager",
        subteam: "Corporate Communications",
        Department: null,
        photoUrl: "/Team/Mona_M_S.jpg",
        year: "3rd Year",
        email: "mona.shivakkumar@gmail.com",
        linkedin: "https://www.linkedin.com/in/mona-m-s-10228b300",
        instagram: "https://www.instagram.com/_.mona._.01._/",
        image: Mona_M_S,
        bio: "Leading corporate communication strategies"
      },
      {
        name: "Pranesh S K",
        role: "Manager",
        subteam: "Corporate Communications",
        Department: null,
        photoUrl: "/Team/Pranesh_S_K.jpg",
        year: "3rd Year",
        email: "pranesh26erd@gmail.com",
        linkedin: null,
        instagram: null,
        image: Pranesh_S_K,
        bio: "Coordinating team communications and events"
      },
      {
        name: "Shivam Mishra",
        role: "Manager",
        subteam: "DevOps",
        Department: null,
        photoUrl: "/Team/Shivam_Mishra.jpg",
        year: "3rd Year",
        email: "realshivat2606@gmail.com",
        linkedin: null,
        instagram: null,
        image: Shivam_Mishra,
        bio: "Supporting DevOps projects and technical tasks"
      },
      {
        name: "Tanisha Narasimman",
        role: "Manager",
        subteam: "Corporate Communications",
        Department: null,
        photoUrl: "/Team/Tanisha_Narasimman.jpg",
        year: "3rd Year",
        email: "tanishanarasimman777@gmail.com",
        linkedin: null,
        instagram: null,
        image: Tanisha_Narasimman,
        bio: "Promoting team initiatives through communications"
      },
      {
        name: "Vedavarshini",
        role: "Manager",
        subteam: "Creatives",
        Department: null,
        photoUrl: "/Team/Vedavarshini.jpg",
        year: "3rd Year",
        email: "vedavarshiniv2@gmail.com",
        linkedin: null,
        instagram: null,
        image: Vedavarshini,
        bio: "Crafting creative visuals for team projects"
      },
       {
        name: "Thejashvee",
        role: "Manager",
        subteam: "Corporate Communications",
        Department: null,
        photoUrl: "/Team/Thejashvee.jpg",
        year: "3rd Year",
        email: "thejubabu1@gmail.com",
        linkedin: null,
        instagram: null,
        image: Thejashvee,
        bio: "Enhancing team visibility through communications"
      },
      {
        name: "Sanskar Sharma",
        role: "Deputy Manager",
        subteam: "DevOps",
        Department: "Computer Science and Engineering",
        photoUrl: "/Team/Sanskar_Sharma.jpg",
        year: "2nd Year",
        email: "sharmasanskar7201@gmail.com",
        linkedin: "https://www.linkedin.com/in/sanskar-sharma-0515a9319",
        instagram: "https://www.instagram.com/_sekhar_sharma/",
        image: Sanskar_Sharma,
        bio: "Contributing to DevOps and technical tasks"
      },
       {
        name: "Hasini Thakkallapelly",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Computer Science and Engineering",
        photoUrl: "/Team/Hasini_Thakkallapelly.jpg",
        year: "2nd Year",
        email: "hasini.thakkallapelly34@gmail.com",
        linkedin: "https://www.linkedin.com/in/hasinithakkallapelly/",
        instagram: "https://www.instagram.com/hasini_rufg/",
        image: Hasini_Thakkallapelly,
        bio: "Assisting in corporate communications"
      },
      {
        
        name: "S. Nayan Vamsi",
        role: "Deputy Manager",
        subteam: "DevOps",
        Department: "Computer Science and Engineering",
        photoUrl: "/Team/Nayan_Vamsi.jpg",
        year: "2nd Year",
        email: "nayanvamsi@gmail.com",
        linkedin: "https://www.linkedin.com/in/nayan-vamsi-sunkarapalli-b2a93536b/",
        instagram: "https://www.instagram.com/___nayan__007/",
        image: S_Nayan_Vamsi,
        bio: "Contributing to DevOps and technical development"
      },
      {
        name: "Kamalakannan Ravichandran",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Civil Engineering",
        photoUrl: "/Team/Kamalakannan_R.jpg",
        year: "2nd Year",
        email: "kamalakannanravichandran@gmail.com",
        linkedin: "https://www.linkedin.com/in/kamalakannan-ravichandran-843b662a5",
        instagram: "https://www.instagram.com/kamalakannanravichandran11",
        image: Kamalakannan_Ravichandran,
        bio: "Supporting corporate communications efforts"
      },
      {
        name: "Chebrolu Bhuvan",
        role: "Deputy Manager",
        subteam: "DevOps",
        Department: "Computer Science and Engineering",
        photoUrl: "/Team/Chebrolu_Bhuvan.jpg",
        year: "2nd Year",
        email: "bhuvanchebrolu@gmail.com",
        linkedin: "https://www.linkedin.com/in/bhuvan-chebrolu-5835641b2/",
        instagram: "https://www.instagram.com/bhuvaneshwar2966/",
        image: Chebrolu_Bhuvan,
        bio: "Assisting in DevOps projects and technical tasks"
      },
      {
        name: "S. Janani Krithika",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Civil Engineering",
        photoUrl: "/Team/S_Janani_Krithika.jpg",
        year: "2nd Year",
        email: "jananikrithika9@gmail.com",
        linkedin: "https://www.linkedin.com/in/janani-krithika-26b019334",
        instagram: "https://www.instagram.com/janani.krithika/",
        image: S_janani,
        bio: "Contributing to team outreach and communications"
      },
      {
        name: "Bhuvan Prakash",
        role: "Deputy Manager",
        subteam: "DevOps",
        Department: "Computer Science and Engineering",
        photoUrl: "/Team/Bhuvan_prakash.jpg",
        year: "2nd Year",
        email: "bhuvanprakash06@gmail.com",
        linkedin: "https://www.linkedin.com/in/bhuvan-prakash-b20a7a379",
        instagram: "https://www.instagram.com/bhuvan._prakash/",
        image: Bhuvan_prakash,
        bio: "Supporting DevOps initiatives and technical projects"
      },
      {
        name: "Pavithra M A",
        role: "Deputy Manager",
        subteam: "Creatives",
        Department: "Electronics and Communication Engineering",
        photoUrl: "/Team/Pavithra_M_A.jpg",
        year: "2nd Year",
        email: "pavithra55ma@gmail.com",
        linkedin: "https://www.linkedin.com/in/pavithra-m-a-b52476324",
        instagram: "https://www.instagram.com/pavithra_m_a",
        image: Pavithra,
        bio: "Designing creative content for team initiatives"
      },
      {
        name: "Aryan Nagle",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Instrumentation and Control Engineering",
        photoUrl: "/Team/Aryan_Nagle.jpg",
        year: "2nd Year",
        email: "aryannagle362@gmail.com",
        linkedin: "https://www.linkedin.com/in/aryan-nagle-a22840343",
        instagram: "https://www.instagram.com/a_ryann06/",
        image: Aryan_Nagle,
        bio: "Assisting in corporate communications and events"
      },
      {
        name: "Bhuvaneswaran B R",
        role: "Deputy Manager",
        subteam: "Creatives",
        Department: "Metallurgical and Materials Engineering",
        photoUrl: "/Team/Bhuvaneswaran_B_R.jpg",
        year: "2nd Year",
        email: "bhuvaneswaranbr@gmail.com",
        linkedin: "https://www.linkedin.com/in/bhuvaneswaran-b-r-7b5725322",
        instagram: "https://www.instagram.com/i__am_bhuvi02",
        image: Bhuvaneswaran_B_R,
        bio: "Creating visuals for team projects and events"
      },
      {
        name: "Nandhana V",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Metallurgical and Materials Engineering",
        photoUrl: "/Team/Nandhana_V.jpg",
        year: "2nd Year",
        email: "nandhanav2006@gmail.com",
        linkedin: "https://www.linkedin.com/in/nandhana-v-312a81379/",
        instagram: "https://www.instagram.com/_nandhana_v/",
        image: Nandhana_V,
        bio: "Supporting team communication strategies"
      },
      {
        name: "Vishal Durai",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Metallurgical and Materials Engineering",
        photoUrl: "/Team/Vishal.jpg",
        year: "2nd Year",
        email: "vishaldurai06@gmail.com",
        linkedin: "https://www.linkedin.com/in/vishal-d-7ab937312",
        instagram: "https://www.instagram.com/_._vizhal_._",
        image: Vishal_Durai,
        bio: "Contributing to team outreach efforts"
      },
      {
        name: "Vaidya Nilay Vivek",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Electrical and Electronics Engineering",
        photoUrl: "/Team/Vaidya_Nilay_Vivek.jpg",
        year: "2nd Year",
        email: "nilayvaidya2005@gmail.com",
        linkedin: "https://www.linkedin.com/in/nilay-vaidya-051993333",
        instagram: "https://www.instagram.com/nilay0341",
        image: Vaidya_Nilay_Vivek,
        bio: "Supporting team outreach and communications"
      },
      {
        name: "Muhesh Alagappan Thiyagarajan",
        role: "Deputy Manager",
        subteam: "Creatives",
        Department: "Electrical and Electronics Engineering",
        photoUrl: "/Team/Muhesh.jpg",
        year: "2nd Year",
        email: "muheshat416@gmail.com",
        linkedin: "https://www.linkedin.com/in/muhesh-a-t-39b0aa354/",
        instagram: "https://www.instagram.com/mu.he.sh/",
        image: Muhesh_Alagappan_Thiyagarajan,
        bio: "Crafting creative designs for team initiatives"
      },
      {
        name: "Lakshana S",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Electrical and Electronics Engineering",
        photoUrl: "/Team/Lakshana.jpg",
        year: "2nd Year",
        email: "lakshana4486@gmail.com",
        linkedin: "https://www.linkedin.com/in/lakshana-s-aa437a326/",
        instagram: "https://www.instagram.com/lakshana2848",
        image: Lakshana_S,
        bio: "Assisting in team communication efforts"
      },
      {
        name: "Priyanshu Mahajan",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Instrumentation and Control Engineering",
        photoUrl: "/Team/default.jpg",
        year: "2nd Year",
        email: "priyanshumahajan6@gmail.com",
        linkedin: "https://www.linkedin.com/in/priyanshu-mahajan-102a14379",
        instagram: "https://www.instagram.com/priyanshu.mahajan_",
        image: null,
        bio: "Contributing to corporate communications"
      },
      {
        name: "Jatin Suresh Subramani",
        role: "Deputy Manager",
        subteam: "Creatives",
        Department: "Architecture",
        photoUrl: "/Team/Jatin_S_S.jpg",
        year: "2nd Year",
        email: "jatinsuresh5647@gmail.com",
        linkedin: "https://www.linkedin.com/in/jatin-suresh-a732bb309",
        instagram: null,
        image: Jatin_S_S,
        bio: "Designing visuals for team projects"
      },
      {
        name: "Poluru Saketh Koundinya",
        role: "Deputy Manager",
        subteam: "DevOps",
        Department: "Computer Science and Engineering",
        photoUrl: "/Team/Saketh.jpg",
        year: "2nd Year",
        email: "polurusaketh@gmail.com",
        linkedin: "https://www.linkedin.com/in/saketh-poluru-515b91315",
        instagram: "https://www.instagram.com/granger__47",
        image: Poluru_Saketh_Koundinya,
        bio: "Supporting DevOps and technical development"
      },
      {
        name: "Samarth Pattewar",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Instrumentation and Control Engineering",
        photoUrl: "/Team/Samarth.jpg",
        year: "2nd Year",
        email: "samarthbpattewar@gmail.com",
        linkedin: "https://www.linkedin.com/in/samarth-pattewar-64191034a",
        instagram: "https://www.instagram.com/psam_arth",
        image: samarth,
        bio: "Assisting in team outreach and communications"
      },
      {
        name: "Muhammad Yousuf",
        role: "Deputy Manager",
        subteam: "Creatives",
        Department: "Architecture",
        photoUrl: "/Team/Muhammad_Yousuf.jpg",
        year: "2nd Year",
        email: "muhammadyousuf5winners@gmail.com",
        linkedin: null,
        instagram: "https://www.instagram.com/__you._.suf",
        image: Muhammad_Yousuf,
        bio: "Creating engaging visual content"
      },
      {
        name: "Meeduti Rithwik Sundar",
        role: "Deputy Manager",
        subteam: "Creatives",
        Department: "Architecture",
        photoUrl: "/Team/M_Rithwik_Sundar.jpg",
        year: "2nd Year",
        email: "srinivasreddykaripireddy566@gmail.com",
        linkedin: "https://www.linkedin.com/in/meeduri-rithwik-002172329",
        instagram: null,
        image: M_Rithwik_Sundar,
        bio: "Contributing to creative design projects"
      },
      {
        name: "Jayasri R",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Civil Engineering",
        photoUrl: "/Team/Jayasri_R.jpg",
        year: "2nd Year",
        email: "jayasrijha2006@gmail.com",
        linkedin: "https://in.linkedin.com/in/jayasri-rajasundaram-143a4a291",
        instagram: "https://www.instagram.com/jayasri_jerry22",
        image: Jayasri_R,
        bio: "Supporting corporate communications"
      },
      {
        name: "Harshitha R",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Computer Science and Engineering",
        photoUrl: "/Team/Harshitha_R.jpg",
        year: "2nd Year",
        email: "harshitharaman123@gmail.com",
        linkedin: null,
        instagram: "https://www.instagram.com/harshey238",
        image: harshita,
        bio: "Assisting in team communication efforts"
      },
      {
        name: "Krishvinraam Mohan",
        role: "Deputy Manager",
        subteam: "DevOps",
        Department: "Production Engineering",
        photoUrl: "/Team/default.jpg",
        year: "2nd Year",
        email: "krishvinraam3@gmail.com",
        linkedin: "https://www.linkedin.com/in/krishvinraam-mohan-5a82261ab/",
        instagram: "https://www.instagram.com/krishvin_3_/",
        image: null,
        bio: "Contributing to DevOps and technical projects"
      },
      {
        name: "Monashri S",
        role: "Deputy Manager",
        subteam: "Creatives",
        Department: "Metallurgical and Materials Engineering",
        photoUrl: "/Team/Monashri_S.jpg",
        year: "2nd Year",
        email: "mshrismail@gmail.com",
        linkedin: "https://www.linkedin.com/in/monashri-s-1b900b37a",
        instagram: "https://www.instagram.com/monashri_._",
        image: Monashri_S,
        bio: "Crafting creative visuals for the team"
      },
      {
        name: "Swathi Chokalingam",
        role: "Deputy Manager",
        subteam: "Corporate Communications",
        Department: "Electrical and Electronics Engineering",
        photoUrl: "/Team/Swathi_Chokalingam.jpg",
        year: "2nd Year",
        email: "swathinit2028@gmail.com",
        linkedin: "https://www.linkedin.com/in/swathi-chokalingam-590b39379",
        instagram: "https://www.instagram.com/swathi_chok",
        image: Swathi_Chokalingam,
        bio: "Supporting team outreach and communications"
      },
      {
        name: "Ankur Das",
        role: "Ex-Manager",
        subteam: null,
        Department: null,
        photoUrl: "/Team/default.jpg",
        year: "4th/5th Year",
        email: "ankurdasbusiness@gmail.com",
        linkedin: null,
        instagram: null,
        image: null,
        bio: "Managed team operations and projects"
      },
      {
        name: "Arshad Ahmed",
        role: "Ex-Manager",
        subteam: null,
        Department: null,
        photoUrl: "/Team/default.jpg",
        year: "4th/5th Year",
        email: "a.arshad2003@gmail.com",
        linkedin: null,
        instagram: null,
        image: null,
        bio: "Supported team management and initiatives"
      },
      {
        name: "E Aditya",
        role: "Ex-Manager",
        subteam: null,
        Department: null,
        photoUrl: "/Team/default.jpg",
        year: "4th/5th Year",
        email: "aditya.eswaran1410@gmail.com",
        linkedin: null,
        instagram: null,
        image: null,
        bio: "Contributed to team leadership and coordination"
      },
      {
        name: "Inbazhagan R",
        role: "Ex-Manager",
        subteam: null,
        Department: null,
        photoUrl: "/Team/default.jpg",
        year: "4th/5th Year",
        email: "inbazhagan.nitt@gmail.com",
        linkedin: null,
        instagram: null,
        image: null,
        bio: "Led team efforts in project management"
      },
      {
        name: "Niranjan Kumaar M",
        role: "Ex-Manager",
        subteam: null,
        Department: null,
        photoUrl: "/Team/default.jpg",
        year: "4th/5th Year",
        email: "bruhdidntcope@gmail.com",
        linkedin: null,
        instagram: null,
        image: null,
        bio: "Supported team operations and planning"
      },
      {
        name: "Sree Harine Harikrishna Perumal",
        role: "Ex-Manager",
        subteam: null,
        Department: null,
        photoUrl: "/Team/default.jpg",
        year: "4th/5th Year",
        email: "sreeharineharikrishnaperumal@gmail.com",
        linkedin: null,
        instagram: null,
        image: null,
        bio: "Contributed to team management and events"
      },
      {
        name: "Tejasvini Gunda",
        role: "Ex-Manager",
        subteam: null,
        Department: null,
        photoUrl: "/Team/default.jpg",
        year: "4th/5th Year",
        email: "tejasvinigunda@gmail.com",
        linkedin: null,
        instagram: null,
        image: null,
        bio: "Managed team projects and coordination"
      }
];

const seedDB = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ MongoDB connected");

    await TeamMember.deleteMany({});
    console.log("🧹 Old data cleared");

    await TeamMember.insertMany(teamData);
    console.log("🌱 Team data seeded successfully!");

    mongoose.connection.close();
  } catch (err) {
    console.error("❌ Error seeding database:", err);
    mongoose.connection.close();
  }
};

seedDB();